# Generated by Django 3.0.5 on 2020-05-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_eval_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eval',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
